name: Update Movebank Data and Deploy Map

on:
  schedule:
    - cron: '0 */6 * * *'  # Corre cada 6 horas
  workflow_dispatch:  # Permite ejecución manual

jobs:
  update-movebank:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libpng-dev gdal-bin libgdal-dev pandoc

    - name: Instalar paquetes R
      run: |
        Rscript -e 'if (!requireNamespace("pacman", quietly = TRUE)) install.packages("pacman")'
        Rscript -e 'pacman::p_load(dplyr, lubridate, move, leaflet, htmlwidgets, jsonlite, remotes)'
        Rscript -e 'if (!"move" %in% installed.packages()[,"Package"]) remotes::install_version("move", version = "4.0.6", repos = "http://cran.us.r-project.org")'

    - name: Limpiar archivos anteriores
      run: |
        rm -rf docs/*
        git rm -rf docs/* || true  # Asegura que Git los detecte como eliminados

    - name: Ejecutar script de actualización y generación de mapa
      run: |
        Rscript main_script.R
      env:
        MOVEBANK_USER: ${{ secrets.MOVEBANK_USER }}
        MOVEBANK_PASS: ${{ secrets.MOVEBANK_PASS }}

    - name: Verificar archivos generados
      run: |
        ls -l docs/
        if [ ! -s docs/index.html ]; then
          echo "Error: docs/index.html no se generó."
          exit 1
        fi

    - name: Subir cambios a GitHub
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add -A
        git commit -m "Actualización automática de datos Movebank y mapa interactivo" --allow-empty
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
