name: Actualizar datos Movebank

on:
  schedule:
    - cron: '0 */12 * * *'  # Ejecutar cada 12 horas
  workflow_dispatch:  # Permite ejecución manual

jobs:
  update-movebank:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libpng-dev gdal-bin libgdal-dev pandoc

    - name: Instalar paquetes R
      run: |
        Rscript -e 'if (!requireNamespace("pacman", quietly = TRUE)) install.packages("pacman")'
        Rscript -e 'pacman::p_load(dplyr, lubridate, move, leaflet, htmlwidgets, jsonlite, remotes)'
        Rscript -e 'if (!"move" %in% installed.packages()[,"Package"]) remotes::install_version("move", version = "4.0.6", repos = "http://cran.us.r-project.org")'

    - name: Eliminar archivos previos si existen
      run: |
        rm -f gps_data.csv gps_data.json
        rm -rf docs/index.html docs/index_files

    - name: Descargar datos de Movebank
      run: |
        Rscript 00_Download_data_Movebank.R

        # Verificar que el archivo se ha creado y tiene contenido
        if [ ! -s gps_data.csv ]; then
          echo "Error: gps_data.csv no se generó o está vacío."
          exit 1
        fi
      env:
        MOVEBANK_USER: ${{ secrets.MOVEBANK_USER }}
        MOVEBANK_PASS: ${{ secrets.MOVEBANK_PASS }}

    - name: Preparar directorio de salida
      run: mkdir -p docs/

    - name: Generar mapa interactivo
      run: |
        set -e
        Rscript 01_Interactive_map.R

        # Mover index_files/ a docs/ si existe
        if [ -d "index_files" ]; then
          mv -u index_files docs/
        fi

        # Verificar que index.html se generó correctamente
        if [ ! -s docs/index.html ]; then
          echo "Error: docs/index.html está vacío o no se generó."
          exit 1
        fi

    - name: Subir cambios a GitHub
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/BioChess/Interactive_map_web.git

        # Resetear y traer últimos cambios para evitar conflictos
        git fetch origin main
        git reset --hard origin/main

        # Agregar archivos generados
        git add gps_data.csv gps_data.json docs/index.html || true
        if [ -d "docs/index_files" ]; then
          git add docs/index_files/
        fi

        # Hacer commit si hay cambios
        git diff --quiet && git diff --staged --quiet || git commit -m "Actualización automática de datos Movebank y mapa interactivo"

        # Hacer push
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



