name: Actualizar datos Movebank

on:
  schedule:
    - cron: '0 */4 * * *'  # Ejecutar cada 4 horas
  workflow_dispatch:  # Permite ejecución manual

jobs:
  update-movebank:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libpng-dev gdal-bin libgdal-dev pandoc

    - name: Instalar paquetes R
      run: |
        Rscript -e 'if (!requireNamespace("pacman", quietly = TRUE)) install.packages("pacman")'
        Rscript -e 'pacman::p_load(dplyr, lubridate, move, leaflet, htmlwidgets, jsonlite, remotes)'
        Rscript -e 'if (!"move" %in% installed.packages()[,"Package"]) remotes::install_version("move", version = "4.0.6", repos = "http://cran.us.r-project.org")'

    - name: Limpiar archivos anteriores
      run: |
        rm -f gps_data.csv gps_data.json
        rm -f docs/index.html
        rm -rf docs/index_files
        mkdir -p docs  # Crea la carpeta si no existe

    - name: Descargar datos de Movebank
      run: |
        Rscript 00_Download_data_Movebank.R

        # Verificar si se creó el archivo correctamente
        if [ ! -s gps_data.csv ]; then
          echo "Error: gps_data.csv no se generó o está vacío."
          exit 1
        fi
      env:
        MOVEBANK_USER: ${{ secrets.MOVEBANK_USER }}
        MOVEBANK_PASS: ${{ secrets.MOVEBANK_PASS }}

    - name: Generar mapa interactivo
      run: |
        Rscript 01_Interactive_map.R

        # Mover archivos HTML si existen
        if [ -d "index_files" ]; then
          mv -u index_files docs/
        fi

        if [ ! -s docs/index.html ]; then
          echo "Error: docs/index.html no se generó correctamente."
          exit 1
        fi

    - name: Subir cambios a GitHub
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/BioChess/Interactive_map_web.git

        git fetch origin main
        git reset --hard origin/main

        git add -A
        git commit -m "Forzando actualización de archivos Leaflet y datos GPS" || echo "Sin cambios para hacer commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

