name: Actualizar datos Movebank

on:
  schedule:
    - cron: '0 0 * * *' # Ejecuta el script todos los días a la medianoche UTC
  workflow_dispatch: # Permite ejecutar manualmente

jobs:
  update-movebank:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libpng-dev gdal-bin libgdal-dev
        

    - name: Instalar paquetes R (solo si no están instalados)
      run: |
        Rscript -e 'packages <- c("pacman", "dplyr", "lubridate", "move", "leaflet", "htmlwidgets", "jsonlite");
                 new.packages <- packages[!(packages %in% installed.packages()[,"Package"])];
                 if(length(new.packages)) install.packages(new.packages, dependencies=TRUE)'
        Rscript -e 'if (!"move" %in% installed.packages()[,"Package"]) remotes::install_version("move", version = "4.0.6", repos = "http://cran.us.r-project.org")'

    - name: Run R script
      run: Rscript 00_Download_data_Movebank.R
      env:
        MOVEBANK_USER: ${{ secrets.MOVEBANK_USER }}
        MOVEBANK_PASSWORD: ${{ secrets.MOVEBANK_PASSWORD }}

    - name: Subir cambios a GitHub
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add gps_data.csv gps_data.json
        git commit -m "Actualización automática de datos Movebank" || echo "Sin cambios"
        git push
