name: Actualizar datos Movebank

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecuta el script todos los días a medianoche UTC

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      MOVEBANK_USER: ${{ secrets.MOVEBANK_USER }}
      MOVEBANK_PASS: ${{ secrets.MOVEBANK_PASS }}

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Instalar paquetes R
        run: |
          Rscript -e 'install.packages(c("pacman", "dplyr", "lubridate", "move", "jsonlite"))'

      - name: Ejecutar script de R
        run: Rscript 00_Download_data_Movebank.R  

      - name: Subir cambios a GitHub
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add gps_data.csv gps_data.json
          git commit -m "Actualización automática de datos Movebank" || echo "Sin cambios"
          git push
